#WAP to create a file & print the file content
x=input("Enter the File Name = ")
r=open("D:/Python/Pranab Sir 1/File Handling/"+x,"w")
a=input("Enter the Sentence = ")
r.write(a)
r.write("\n")
a=input("Enter the 2nd Sentence = ")
r.write(a)
r.close()
r=open("D:/Python/Pranab Sir 1/File Handling/"+x,"r")
print(r.read())
r.close()