r=open("D:/Python/Pranab Sir 1/File Handling/Arisha.txt","w")
x=input("Enter the Sentence= ")
r.write(x)
r.write("\n")
y=input("Enter the 2nd Sentence= ")
r.write(y)
r.close()
r=open("D:/Python/Pranab Sir 1/File Handling/Arisha.txt","r")
print(r.read())
r.close()